# Generated by Django 5.2 on 2025-04-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_savedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
